[package]
name = "open-coroutine-scheduler"
version = "0.1.0"
edition = "2021"

[dependencies]
object-list = { path = "../object-list" }
timer = { path = "../timer" }
open-coroutine = { path = "../open-coroutine" }
once_cell = "1.13.0"